<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: points.proto

namespace Points;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>points.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string yz_open_id = 1;</code>
     */
    private $yz_open_id = '';
    /**
     * Generated from protobuf field <code>int32 points = 2;</code>
     */
    private $points = 0;
    /**
     * Generated from protobuf field <code>string reason = 3;</code>
     */
    private $reason = '';
    /**
     * Generated from protobuf field <code>int32 page = 4;</code>
     */
    private $page = 0;
    /**
     * Generated from protobuf field <code>int32 limit = 5;</code>
     */
    private $limit = 0;
    /**
     * Generated from protobuf field <code>string start_date = 6;</code>
     */
    private $start_date = '';
    /**
     * Generated from protobuf field <code>string end_date = 7;</code>
     */
    private $end_date = '';
    /**
     * Generated from protobuf field <code>int64 userid = 8;</code>
     */
    private $userid = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $yz_open_id
     *     @type int $points
     *     @type string $reason
     *     @type int $page
     *     @type int $limit
     *     @type string $start_date
     *     @type string $end_date
     *     @type int|string $userid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Points::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string yz_open_id = 1;</code>
     * @return string
     */
    public function getYzOpenId()
    {
        return $this->yz_open_id;
    }

    /**
     * Generated from protobuf field <code>string yz_open_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setYzOpenId($var)
    {
        GPBUtil::checkString($var, True);
        $this->yz_open_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 points = 2;</code>
     * @return int
     */
    public function getPoints()
    {
        return $this->points;
    }

    /**
     * Generated from protobuf field <code>int32 points = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPoints($var)
    {
        GPBUtil::checkInt32($var);
        $this->points = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reason = 3;</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>string reason = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->reason = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page = 4;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int32 page = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 5;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string start_date = 6;</code>
     * @return string
     */
    public function getStartDate()
    {
        return $this->start_date;
    }

    /**
     * Generated from protobuf field <code>string start_date = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setStartDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string end_date = 7;</code>
     * @return string
     */
    public function getEndDate()
    {
        return $this->end_date;
    }

    /**
     * Generated from protobuf field <code>string end_date = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setEndDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 userid = 8;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     * Generated from protobuf field <code>int64 userid = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;

        return $this;
    }

}

