<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace GPBMetadata;

class Auth
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab2020a0a617574682e70726f746f12046175746822370a075265717565" .
            "7374120e0a06757365726964180120012803120d0a0570686f6e65180220" .
            "012809120d0a05746f6b656e18032001280922340a08526573706f6e7365" .
            "120c0a04636f6465180120012805120b0a036d7367180220012809120d0a" .
            "05746f6b656e18032001280932a6010a044175746812320a0f4d616b6541" .
            "6363657373546f6b656e120d2e617574682e526571756573741a0e2e6175" .
            "74682e526573706f6e7365220012350a1244656c55736572416363657373" .
            "546f6b656e120d2e617574682e526571756573741a0e2e617574682e5265" .
            "73706f6e7365220012330a10436865636b416363657373546f6b656e120d" .
            "2e617574682e526571756573741a0e2e617574682e526573706f6e736522" .
            "00620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

