<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vipuser.proto

namespace Vipuser;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vipuser.RequestBrankCard</code>
 */
class RequestBrankCard extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 userid = 1;</code>
     */
    private $userid = 0;
    /**
     * Generated from protobuf field <code>int64 bankcard_id = 2;</code>
     */
    private $bankcard_id = 0;
    /**
     * Generated from protobuf field <code>string bank_name = 3;</code>
     */
    private $bank_name = '';
    /**
     * Generated from protobuf field <code>string bank_card = 4;</code>
     */
    private $bank_card = '';
    /**
     * Generated from protobuf field <code>string account_area = 5;</code>
     */
    private $account_area = '';
    /**
     * Generated from protobuf field <code>string bank_branch = 6;</code>
     */
    private $bank_branch = '';
    /**
     * Generated from protobuf field <code>string bank = 7;</code>
     */
    private $bank = '';
    /**
     * Generated from protobuf field <code>string mobile = 8;</code>
     */
    private $mobile = '';
    /**
     * Generated from protobuf field <code>string weixin = 9;</code>
     */
    private $weixin = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $userid
     *     @type int|string $bankcard_id
     *     @type string $bank_name
     *     @type string $bank_card
     *     @type string $account_area
     *     @type string $bank_branch
     *     @type string $bank
     *     @type string $mobile
     *     @type string $weixin
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vipuser::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 bankcard_id = 2;</code>
     * @return int|string
     */
    public function getBankcardId()
    {
        return $this->bankcard_id;
    }

    /**
     * Generated from protobuf field <code>int64 bankcard_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBankcardId($var)
    {
        GPBUtil::checkInt64($var);
        $this->bankcard_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bank_name = 3;</code>
     * @return string
     */
    public function getBankName()
    {
        return $this->bank_name;
    }

    /**
     * Generated from protobuf field <code>string bank_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBankName($var)
    {
        GPBUtil::checkString($var, True);
        $this->bank_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bank_card = 4;</code>
     * @return string
     */
    public function getBankCard()
    {
        return $this->bank_card;
    }

    /**
     * Generated from protobuf field <code>string bank_card = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBankCard($var)
    {
        GPBUtil::checkString($var, True);
        $this->bank_card = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string account_area = 5;</code>
     * @return string
     */
    public function getAccountArea()
    {
        return $this->account_area;
    }

    /**
     * Generated from protobuf field <code>string account_area = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAccountArea($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_area = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bank_branch = 6;</code>
     * @return string
     */
    public function getBankBranch()
    {
        return $this->bank_branch;
    }

    /**
     * Generated from protobuf field <code>string bank_branch = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBankBranch($var)
    {
        GPBUtil::checkString($var, True);
        $this->bank_branch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bank = 7;</code>
     * @return string
     */
    public function getBank()
    {
        return $this->bank;
    }

    /**
     * Generated from protobuf field <code>string bank = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setBank($var)
    {
        GPBUtil::checkString($var, True);
        $this->bank = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mobile = 8;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     * Generated from protobuf field <code>string mobile = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string weixin = 9;</code>
     * @return string
     */
    public function getWeixin()
    {
        return $this->weixin;
    }

    /**
     * Generated from protobuf field <code>string weixin = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setWeixin($var)
    {
        GPBUtil::checkString($var, True);
        $this->weixin = $var;

        return $this;
    }

}

