<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vipuser.proto

namespace Vipuser;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vipuser.RequestTakeNotes</code>
 */
class RequestTakeNotes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 userid = 1;</code>
     */
    private $userid = 0;
    /**
     * Generated from protobuf field <code>double money = 2;</code>
     */
    private $money = 0.0;
    /**
     * Generated from protobuf field <code>string remarks = 3;</code>
     */
    private $remarks = '';
    /**
     * Generated from protobuf field <code>int64 bankcard_id = 4;</code>
     */
    private $bankcard_id = 0;
    /**
     * Generated from protobuf field <code>int32 page = 5;</code>
     */
    private $page = 0;
    /**
     * Generated from protobuf field <code>int32 page_size = 6;</code>
     */
    private $page_size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $userid
     *     @type float $money
     *     @type string $remarks
     *     @type int|string $bankcard_id
     *     @type int $page
     *     @type int $page_size
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vipuser::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double money = 2;</code>
     * @return float
     */
    public function getMoney()
    {
        return $this->money;
    }

    /**
     * Generated from protobuf field <code>double money = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setMoney($var)
    {
        GPBUtil::checkDouble($var);
        $this->money = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string remarks = 3;</code>
     * @return string
     */
    public function getRemarks()
    {
        return $this->remarks;
    }

    /**
     * Generated from protobuf field <code>string remarks = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRemarks($var)
    {
        GPBUtil::checkString($var, True);
        $this->remarks = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 bankcard_id = 4;</code>
     * @return int|string
     */
    public function getBankcardId()
    {
        return $this->bankcard_id;
    }

    /**
     * Generated from protobuf field <code>int64 bankcard_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBankcardId($var)
    {
        GPBUtil::checkInt64($var);
        $this->bankcard_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page = 5;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int32 page = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 6;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

}

