<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vipuser.proto

namespace Vipuser;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vipuser.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string mobile = 1;</code>
     */
    private $mobile = '';
    /**
     * Generated from protobuf field <code>string pwd = 2;</code>
     */
    private $pwd = '';
    /**
     * Generated from protobuf field <code>int32 page = 3;</code>
     */
    private $page = 0;
    /**
     * Generated from protobuf field <code>int32 page_size = 4;</code>
     */
    private $page_size = 0;
    /**
     * Generated from protobuf field <code>int64 create_at = 5;</code>
     */
    private $create_at = 0;
    /**
     * Generated from protobuf field <code>int32 level = 6;</code>
     */
    private $level = 0;
    /**
     * Generated from protobuf field <code>string sort = 7;</code>
     */
    private $sort = '';
    /**
     * Generated from protobuf field <code>string from_buyer_mobile = 8;</code>
     */
    private $from_buyer_mobile = '';
    /**
     * Generated from protobuf field <code>int64 starttime = 9;</code>
     */
    private $starttime = 0;
    /**
     * Generated from protobuf field <code>int64 endtime = 10;</code>
     */
    private $endtime = 0;
    /**
     * Generated from protobuf field <code>int64 userid = 11;</code>
     */
    private $userid = 0;
    /**
     * Generated from protobuf field <code>string openid = 12;</code>
     */
    private $openid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $mobile
     *     @type string $pwd
     *     @type int $page
     *     @type int $page_size
     *     @type int|string $create_at
     *     @type int $level
     *     @type string $sort
     *     @type string $from_buyer_mobile
     *     @type int|string $starttime
     *     @type int|string $endtime
     *     @type int|string $userid
     *     @type string $openid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vipuser::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pwd = 2;</code>
     * @return string
     */
    public function getPwd()
    {
        return $this->pwd;
    }

    /**
     * Generated from protobuf field <code>string pwd = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPwd($var)
    {
        GPBUtil::checkString($var, True);
        $this->pwd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page = 3;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int32 page = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 4;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 create_at = 5;</code>
     * @return int|string
     */
    public function getCreateAt()
    {
        return $this->create_at;
    }

    /**
     * Generated from protobuf field <code>int64 create_at = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->create_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 level = 6;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>int32 level = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sort = 7;</code>
     * @return string
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     * Generated from protobuf field <code>string sort = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSort($var)
    {
        GPBUtil::checkString($var, True);
        $this->sort = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string from_buyer_mobile = 8;</code>
     * @return string
     */
    public function getFromBuyerMobile()
    {
        return $this->from_buyer_mobile;
    }

    /**
     * Generated from protobuf field <code>string from_buyer_mobile = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setFromBuyerMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->from_buyer_mobile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 starttime = 9;</code>
     * @return int|string
     */
    public function getStarttime()
    {
        return $this->starttime;
    }

    /**
     * Generated from protobuf field <code>int64 starttime = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStarttime($var)
    {
        GPBUtil::checkInt64($var);
        $this->starttime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 endtime = 10;</code>
     * @return int|string
     */
    public function getEndtime()
    {
        return $this->endtime;
    }

    /**
     * Generated from protobuf field <code>int64 endtime = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndtime($var)
    {
        GPBUtil::checkInt64($var);
        $this->endtime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 userid = 11;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     * Generated from protobuf field <code>int64 userid = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string openid = 12;</code>
     * @return string
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     * Generated from protobuf field <code>string openid = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenid($var)
    {
        GPBUtil::checkString($var, True);
        $this->openid = $var;

        return $this;
    }

}

