<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: promocode.proto

namespace Promocode;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>promocode.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string title = 1;</code>
     */
    private $title = '';
    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     */
    private $total = 0;
    /**
     * Generated from protobuf field <code>int32 cent_value = 3;</code>
     */
    private $cent_value = 0;
    /**
     * Generated from protobuf field <code>string code_type = 4;</code>
     */
    private $code_type = '';
    /**
     * Generated from protobuf field <code>string range_type = 5;</code>
     */
    private $range_type = '';
    /**
     * Generated from protobuf field <code>string phone = 6;</code>
     */
    private $phone = '';
    /**
     * Generated from protobuf field <code>int64 coupon_group_id = 7;</code>
     */
    private $coupon_group_id = 0;
    /**
     * Generated from protobuf field <code>int32 page = 8;</code>
     */
    private $page = 0;
    /**
     * Generated from protobuf field <code>int32 limit = 9;</code>
     */
    private $limit = 0;
    /**
     * Generated from protobuf field <code>string group_type = 10;</code>
     */
    private $group_type = '';
    /**
     * Generated from protobuf field <code>string status = 11;</code>
     */
    private $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *     @type int $total
     *     @type int $cent_value
     *     @type string $code_type
     *     @type string $range_type
     *     @type string $phone
     *     @type int|string $coupon_group_id
     *     @type int $page
     *     @type int $limit
     *     @type string $group_type
     *     @type string $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Promocode::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt32($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cent_value = 3;</code>
     * @return int
     */
    public function getCentValue()
    {
        return $this->cent_value;
    }

    /**
     * Generated from protobuf field <code>int32 cent_value = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCentValue($var)
    {
        GPBUtil::checkInt32($var);
        $this->cent_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code_type = 4;</code>
     * @return string
     */
    public function getCodeType()
    {
        return $this->code_type;
    }

    /**
     * Generated from protobuf field <code>string code_type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCodeType($var)
    {
        GPBUtil::checkString($var, True);
        $this->code_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string range_type = 5;</code>
     * @return string
     */
    public function getRangeType()
    {
        return $this->range_type;
    }

    /**
     * Generated from protobuf field <code>string range_type = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRangeType($var)
    {
        GPBUtil::checkString($var, True);
        $this->range_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone = 6;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>string phone = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 coupon_group_id = 7;</code>
     * @return int|string
     */
    public function getCouponGroupId()
    {
        return $this->coupon_group_id;
    }

    /**
     * Generated from protobuf field <code>int64 coupon_group_id = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCouponGroupId($var)
    {
        GPBUtil::checkInt64($var);
        $this->coupon_group_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page = 8;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int32 page = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 9;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string group_type = 10;</code>
     * @return string
     */
    public function getGroupType()
    {
        return $this->group_type;
    }

    /**
     * Generated from protobuf field <code>string group_type = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupType($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 11;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

}

